### ISSUE TITLE
working since move to tesla.com ?

### ISSUE THREAD

**Issue by bjm88** [hjespers/teslams#110]
I think they changed from teslamotors to just tesla.com recently, I suspect API needs updating too...... is this project currently working.... I was getting an error trying to do login..

Error: login failed
    at /usr/local/lib/node_modules/teslams/examples/teslacmd.js:229:12
    at report (/usr/local/lib/node_modules/teslams/teslams.js:24:13)
    at Request._callback (/usr/local/lib/node_modules/teslams/teslams.js:65:101)
    at Request.self.callback (/usr/local/lib/node_modules/teslams/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/teslams/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/teslams/node_modules/request/request.js:965:12)

**Comment by hjespers** [comment]
It's still working for me. This might have been a temporary problem which is normal with the Tesla authentication server(s)
