### ISSUE TITLE
Cannot call method 'toString' of null

### ISSUE THREAD

**Issue by tris** [hjespers/teslams#115]
```
7 Mar 09:16:17 - 0 of 6 REST requests since 1488906969222
Error parsing response to oauth token request
7 Mar 09:16:17 - Error: unable to parse vehicle data response as JSON, login failed. Trying again.
7 Mar 09:16:27 - 1 of 6 REST requests since 1488906969222
Error parsing response to oauth token request
7 Mar 09:16:27 - Error: unable to parse vehicle data response as JSON, login failed. Trying again.
7 Mar 09:16:37 - 2 of 6 REST requests since 1488906969222
7 Mar 09:16:48 - Info: car is in (asleep) state, will check again in 1 minutes
7 Mar 09:17:09 - Info: car is napping or sleeping, skipping auxiliary REST data sample
7 Mar 09:17:48 - 0 of 6 REST requests since 1488907029226
7 Mar 09:17:55 - Info: car is in (asleep) state, will check again in 1 minutes
7 Mar 09:18:09 - Info: car is napping or sleeping, skipping auxiliary REST data sample
7 Mar 09:18:55 - 0 of 6 REST requests since 1488907089232
7 Mar 09:18:56 - Error: expecting an array if vehicle data from Tesla but got this:

TypeError: Cannot call method 'toString' of null
    at Object.exports.log (util.js:492:42)
    at Request._callback (/usr/lib/node_modules/teslams/examples/streaming.js:659:18)
    at Request.self.callback (/usr/lib/node_modules/teslams/node_modules/request/request.js:186:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/node_modules/teslams/node_modules/request/request.js:1081:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/teslams/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:180:16)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
[1]    20900 exit 8     streaming --db tesla -z
```

**Comment by hjespers** [comment]
hmm. Looks like your car was asleep and then the Tesla service went down so it returned 'null' instead of valid data. I can see about putting some better error handling around this.
